"""add league to player

Revision ID: 949c82f30709
Revises: 366038df315b
Create Date: 2024-08-10 09:31:28.482814

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '949c82f30709'
down_revision = '366038df315b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('league', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'player', 'league', ['league'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'league')
    # ### end Alembic commands ###
